describe("user account control", function() {
    it("creates a user")
    it("doesn't allow incomplete information")
    it("doesn't allow duplicate users")
    it("generates JWT for user")
    it("tests JWT authentication")
    it("changes password")
    it("doesn't allow terrible passwords")
    it("deletes user")
})